#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br> 
  <h3><b>DISTINGUISHED LUXURY</h3></b>
  <br><br>
  <b>ENVISION: THE ULTIMATE MOTORCAR in 3D</b> - Tour 3D Model Below
  <br><br> 
  <b>EXPERIENCE: 4D AUGMENTED REALITY</b> - Open on Mobile Device
  <br><br>
  <b>PERSPECTIVE:</b><a href="https://youtu.be/bgWxVMh-QOk"</b> <b>Discover</b></a> 
  <br><br>
  <b>VISION:</b><a href="https://youtu.be/qLV6cZ5JuZs"</b> <b>Human-Machine Interface</b></a>
  <br><br>
  <b>EXPLORE:</b><a href="https://avertek.net/contact-us"</b> <b>VIP Demo & Free Gift</b></a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
