#title: AVERtek # your name photo (or website title) here
logo1: "Company Here.jpg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br> 
  <b>DISCOVER NEW LUXURY</b>
  <br><br>
  <b>ENVISION: 3D ULTIMATE MOTORCAR</b>- Use pointer to rotate & spin; zoom to scale model below
  <br><br> 
  <b>EXPERIENCE: 4D AUGMENTED REALITY ELEGANCE (on mobile devices only)</b>- press AR button, place image on open flat, well-lit surface, scale & tour
  <br><br>
  <b>VIEW:</b><a href="https://youtu.be/bgWxVMh-QOk"</b> Click here to see what awaits you at Our Dealership</a> 
  <br><br>
  <b>EXPLORE:</b><a href="https://avertek.net/contact-us"</b> Click here for our Private VIP Presentation & receive a special gift</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
