#title: AVERtek # your name photo (or website title) here
logo1: "/images/Company Here.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  <br><br> 
  <b>##DISCOVER NEW LUXURY</b>
  <br><br>
  <b>ENVISION: 3D ULTIMATE MOTORCARS</b>- Tour 3D Model Below
  <br><br> 
  <b>EXPERIENCE: 4D AUGMENTED REALITY ELEGANCE</b>- Open on Mobile Device for 4D-AR
  <br><br>
  <b>PERSPECTIVE:</b><a href="https://youtu.be/bgWxVMh-QOk"</b> Discover; Click Here</a> 
  <br><br>
  <b>VIEW:</b><a href="https://www.youtube.com/watch?v=F7q56otNy1E"</b> Why Us; Click Here</a>
  <br><br>
  <b>EXPLORE:</b><a href="https://avertek.net/contact-us"</b> Private VIP Demo & Free Gift; Click Here</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: # your Google Analytics tracking ID here
